[project]
name = "alignment"
version = "1.0.0"
description = "CS 336 Spring 2025 Assignment 5: Alignment"
readme = "README.md"
requires-python = ">=3.11,<3.13"  # Python 3.13 not yet supported for some deps
dependencies = [
    "accelerate>=1.5.2",
    "torch",
    "transformers>=4.50.0",
    "tqdm>=4.67.1",
    "typer>=0.15.4",
    "xopen>=2.0.2",
    "math-verify[antlr4-13-2]>=0.7.0",
    "pylatexenc==2.10",
    "pytest>=8.3.5",
    "jupyter>=1.1.1",
    "notebook>=7.4.2",
]

[project.optional-dependencies]
gpu = [
    "vllm==0.7.2",
    "flash-attn==2.7.4.post1",
    "wandb>=0.19.8",
]

[tool.setuptools.packages.find]
include = ["cs336_alignment"]

[tool.uv]
package = true
no-build-isolation-package = ["flash-attn"]


[tool.uv.sources]
alpaca-eval = { git = "https://github.com/nelson-liu/alpaca_eval.git", rev = "forward_kwargs_to_vllm" }

[tool.pytest.ini_options]
log_cli = true
log_cli_level = "WARNING"

[[tool.uv.dependency-metadata]]
name = "flash-attn"
version = "2.7.4.post1"
requires-dist = ["torch", "einops", "setuptools"]
